### PR TITLE
Execution enhancements

### PR DESCRIPTION
**Pull request by curtis-fugue**
# Description

Various enhancements to the configurability of Zim rule execution.

## Rule Conditions

Rules now may have `when` and `unless` conditions defined which control whether the rule commands are to be executed. The implementation is in part inspired by CircleCI's conditions of the same names.

* When and unless both support `resource_exists` and `script_succeeds` checks. The former is met if one or more files or directories match the provided name (or glob pattern) and the latter is met if the specified bash script exits with a 0 status code.
* If the rule condition is not met, the rule is marked as [SKIPPED]. Zim continues executing after this in the same way as if the rule commands all succeeded.

An example:

```yaml
  node_modules:
    requires:
      - rule: node_modules_tgz
    native: true
    commands:
      - run: tar -zxf ${ARTIFACTS_DIR}/${NAME}.node_modules.tgz
    unless:
      resource_exists: node_modules
```

## Artifact environment variables

Rule commands now receive `ARTIFACTS_DIR` and `ARTIFACT` environment variables. These are absolute paths which means rule commands can refer to them easily even after changing directories. These also account for different base paths when the rule command runs inside a Docker container.

## Debug output

Improved and made consistent the extra output that is shown when `--debug` is specified.

## Input files that are not present

Rule inputs are no longer required to be present for the rule to succeed. This allows for more generic base templates for rules where the base template defines a superset of input files. This seems like a better default behavior, especially since the rule key already factors in which input files are present. Later we can add an option to override the default behavior and make certain inputs "required" if we need that option as well.

### CODE REVIEW

**Comment by andrew-luminal** [comment]
💥 💥  Love these changes. Will be testing shortly...

**Review by eric-luminal — APPROVED** [review]
lgtm

**Review by gil-fugue — APPROVED** [review]

**Comment by andrew-luminal** [comment]
For tracking purposes, this addresses #19 and #16. Also addresses the conditional aspect of #15.

**Review by andrew-luminal — APPROVED** [review]
Tested all of the new features, they seem to work! Super excited for them

**Pull request merged**
